
services:
  ssh-tunnel:
    build: .
    ports:
      - "${SSH_EXTERNAL_PORT:-2222}:22"          # SSH port
      - "${HTTP_EXTERNAL_PORT:-8080}:80"         # HTTP port
      - "${HTTPS_EXTERNAL_PORT:-8443}:443"       # HTTPS port
    environment:
      - DOMAIN=${DOMAIN:-localhost}
      - ACME_EMAIL=admin@example.com
      - SSH_PORT=22
      - HTTP_PORT=80
      - HTTPS_PORT=443
      - HTTP_EXTERNAL_PORT=${HTTP_EXTERNAL_PORT:-8080}
      - HTTPS_EXTERNAL_PORT=${HTTPS_EXTERNAL_PORT:-8443}
      - ACME_STAGING=true
      - SSH_AUTHORIZED_KEYS=/data/authorized_keys
    volumes:
      - ./data:/data
    restart: unless-stopped