FROM golang:1.23-alpine

RUN apk add --no-cache curl

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY test/mock-server.go ./

RUN go build -o mock-server mock-server.go

EXPOSE 3000

CMD ["./mock-server"]