
services:
  ssh-tunnel:
    build: .
    ports:
      - "${SSH_EXTERNAL_PORT:-2222}:22"          # SSH port
      - "${HTTP_EXTERNAL_PORT:-8080}:80"         # HTTP port
      - "${HTTPS_EXTERNAL_PORT:-8443}:443"       # HTTPS port
    environment:
      - DOMAIN=${DOMAIN:-localhost}
      - ACME_EMAIL=${ACME_EMAIL:-}
      - SKIP_ACME=${SKIP_ACME:-false}
      - SSH_PORT=22
      - HTTP_PORT=80
      - HTTPS_PORT=443
      - HTTP_EXTERNAL_PORT=${HTTP_EXTERNAL_PORT:-8080}
      - HTTPS_EXTERNAL_PORT=${HTTPS_EXTERNAL_PORT:-8443}
      - ACME_STAGING=${ACME_STAGING:-true}
      - SSH_AUTHORIZED_KEYS=${SSH_AUTHORIZED_KEYS:-/data/authorized_keys}
      - USER_STORAGE_TYPE=${USER_STORAGE_TYPE:-file}
      - USER_STORAGE_PATH=${USER_STORAGE_PATH:-/data/users.json}
      - WEBUI_USERNAME=${WEBUI_USERNAME:-}
      - WEBUI_PASSWORD=${WEBUI_PASSWORD:-}
    volumes:
      - ssh_tunnel_data:/data
    restart: unless-stopped

volumes:
  ssh_tunnel_data: