
services:
  ssh-tunnel:
    build: .
    environment:
      - DOMAIN=tunnel-net
      - ACME_EMAIL=test@example.com
      - SSH_PORT=2222
      - HTTP_PORT=8080
      - HTTPS_PORT=8443
      - ACME_STAGING=true
    volumes:
      - ./data:/data
    networks:
      - tunnel-net
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2222"]
      interval: 5s
      timeout: 3s
      retries: 5

  mock-server:
    build:
      context: .
      dockerfile: Dockerfile.mock
    environment:
      - PORT=3000
    networks:
      - tunnel-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 5s
      timeout: 3s
      retries: 5

networks:
  tunnel-net:
    driver: bridge