services:
  ssh-server:
    build: .
    environment:
      - DOMAIN=ssh-server
      - SKIP_ACME=true
      - SSH_PORT=22
      - HTTP_PORT=80
      - HTTPS_PORT=443
    volumes:
      - e2e_data:/data
      - ./test/test_authorized_keys:/data/authorized_keys:ro
    networks:
      - e2e-net
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "22"]
      interval: 1s
      timeout: 1s
      retries: 5

  e2e-client:
    build:
      context: .
      dockerfile: Dockerfile.e2e-client
    depends_on:
      ssh-server:
        condition: service_healthy
    networks:
      - e2e-net
    volumes:
      - e2e_logs:/logs
    environment:
      - SSH_HOST=ssh-server
      - SSH_PORT=22
      - SAMPLE_SERVER_HOST=localhost
      - SAMPLE_SERVER_PORT=3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 1s
      timeout: 1s
      retries: 5
    command: ["./start-e2e-with-server.sh"]

volumes:
  e2e_data:
  e2e_logs:

networks:
  e2e-net:
    driver: bridge