FROM alpine:latest

RUN apk add --no-cache \
    openssh-client \
    curl \
    bash \
    netcat-openbsd \
    sshpass \
    go

WORKDIR /test

COPY test/ ./
COPY go.mod go.sum ./

RUN go mod download

CMD ["./e2e-test.sh"]